/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tienda.Interfaces;

import Tienda.Interfaces.VentanaCompraCarrito;
import Tienda.Interfaces.VentanaMiHistorial;
import Tienda.Interfaces.VentanaPerfil;
import Tienda.Interfaces.VentanaVerProductos;
import Tienda.PanelFondo;

public class VentanaInicioCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicioCliente.class.getName());

    /**
     * Creates new form VentanaInicioCliente
     */
        public VentanaInicioCliente() {
    setContentPane(new PanelFondo("/Tienda/Imagenes/fondo3.png"));
    initComponents();
    setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/logo_galapa.png")).getImage());

    lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/bienvenida_3.png")));
    lblTitulo.setPreferredSize(new java.awt.Dimension(554, 415));
    lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    int anchoPanel = panelLateral.getWidth();
    getContentPane().remove(panelLateral);
    panelLateral.setBounds(0, 0, anchoPanel, getContentPane().getHeight());
    getLayeredPane().add(panelLateral, javax.swing.JLayeredPane.PALETTE_LAYER);
    panelLateral.setVisible(false);

    // Centrar lblTitulo manualmente (sacándolo del GroupLayout)
    int posY = lblTitulo.getY();
    getContentPane().remove(lblTitulo);
    int anchoVentana = getContentPane().getWidth();
    int posX = (anchoVentana - 554) / 2;
    lblTitulo.setBounds(posX, posY, 554, 415);
    getLayeredPane().add(lblTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

    Tienda.EstiloUI.botonPrimario(btnVerProductos);
    Tienda.EstiloUI.botonPrimario(btnMiCarrito);
    Tienda.EstiloUI.botonPrimario(btnHistorial);

    // Icono del botón de menú (reemplaza el texto "≡")
    btnMenu.setText("");
    btnMenu.setMargin(new java.awt.Insets(0, 0, 0, 0)); // sin márgenes para que el icono quepa completo
    // Tamaño del icono del menú (cámbialo aquí; el botón mide 64x64)
    int tamMenu = 56;
    java.awt.Image imgMenu = new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/menu.png"))
            .getImage().getScaledInstance(tamMenu, tamMenu, java.awt.Image.SCALE_SMOOTH);
    btnMenu.setIcon(new javax.swing.ImageIcon(imgMenu));
    btnMenu.setContentAreaFilled(false);
    btnMenu.setBorderPainted(false);
    btnMenu.setFocusPainted(false);
    btnMenu.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

    // Icono del botón de perfil (mismo tamaño que el del menú)
    java.awt.Image imgPerfil = new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/perfil_usuario.png"))
            .getImage().getScaledInstance(tamMenu, tamMenu, java.awt.Image.SCALE_SMOOTH);
    btnPerfil.setIcon(new javax.swing.ImageIcon(imgPerfil));
    btnPerfil.setMargin(new java.awt.Insets(0, 0, 0, 0));
    btnPerfil.setContentAreaFilled(false);
    btnPerfil.setBorderPainted(false);
    btnPerfil.setFocusPainted(false);
    btnPerfil.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
}
        
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLateral = new javax.swing.JPanel();
        btnVerProductos = new javax.swing.JButton();
        btnMiCarrito = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblTituloBienvenido = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLateral.setForeground(new java.awt.Color(51, 51, 51));

        btnVerProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnVerProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVerProductos.setForeground(new java.awt.Color(0, 0, 0));
        btnVerProductos.setText("Ver Productos");
        btnVerProductos.addActionListener(this::btnVerProductosActionPerformed);

        btnMiCarrito.setBackground(new java.awt.Color(255, 255, 255));
        btnMiCarrito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMiCarrito.setForeground(new java.awt.Color(0, 0, 0));
        btnMiCarrito.setText("Mi carrito");
        btnMiCarrito.addActionListener(this::btnMiCarritoActionPerformed);

        btnHistorial.setBackground(new java.awt.Color(255, 255, 255));
        btnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(0, 0, 0));
        btnHistorial.setText("HIstorial");
        btnHistorial.addActionListener(this::btnHistorialActionPerformed);

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMiCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btnVerProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(btnMiCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/bienvenida_3.png"))); // NOI18N

        lblTituloBienvenido.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/perfil.png"))); // NOI18N
        btnPerfil.addActionListener(this::btnPerfilActionPerformed);

        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenu.setText("≡");
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(616, 616, 616)
                        .addComponent(lblTituloBienvenido)
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblTituloBienvenido)
                        .addGap(75, 75, 75)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(panelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        VentanaPerfil ventana = new VentanaPerfil();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        panelLateral.setVisible(!panelLateral.isVisible());
        panelLateral.setOpaque(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProductosActionPerformed
        // TODO add your handling code here:
        VentanaVerProductos ventana = new VentanaVerProductos();
        ventana.setVisible(true);
        
    }//GEN-LAST:event_btnVerProductosActionPerformed

    private void btnMiCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiCarritoActionPerformed
        // TODO add your handling code here:
        VentanaCompraCarrito ventana = new VentanaCompraCarrito();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnMiCarritoActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        VentanaMiHistorial ventana = new VentanaMiHistorial();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnHistorialActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInicioCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMiCarrito;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnVerProductos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloBienvenido;
    private javax.swing.JPanel panelLateral;
    // End of variables declaration//GEN-END:variables
}
