/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tienda.Interfaces;

import Tienda.Carrito;
import Tienda.Conexion;
import Tienda.ItemCarrito;
import Tienda.PanelFondo;
import Tienda.SesionActual;

/**
 *
 * @author Aprendiz
 */
public class VentanaCompraCarrito extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCompraCarrito.class.getName());

    /**
     * Creates new form VentanaCompraCarrito
     */
    public VentanaCompraCarrito() {
        setContentPane(new PanelFondo("/Tienda/Imagenes/fondo_abarrotes.png"));
    initComponents();
    setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/fondo_abarrotes.png")).getImage());

    Tienda.EstiloUI.botonPrimario(btnComprar);
    Tienda.EstiloUI.botonPeligro(btnEliminar);
    Tienda.EstiloUI.botonSecundario(btnVolver);
    Tienda.EstiloUI.tablaConLogo(tblCarrito, jScrollPane1);

        cargarCarrito();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Ubuntu Mono", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("MI CARRITO");

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Precio", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblCarrito);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total:");

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/_eliminar.png"))); // NOI18N
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/Comprar.png"))); // NOI18N
        btnComprar.addActionListener(this::btnComprarActionPerformed);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/volver.png"))); // NOI18N
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/icono_galapa_.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(171, 171, 171)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(685, 685, 685)
                        .addComponent(btnEliminar)
                        .addGap(37, 37, 37)
                        .addComponent(btnComprar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTotal)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblTitulo)))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnComprar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
if (Carrito.productos.isEmpty()) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "El carrito está vacío."
    );

    return;
}

if (SesionActual.idCliente <= 0) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "No se encontró el cliente de la sesión."
    );

    return;
}

try {

    java.sql.Connection conexion = Conexion.conectar();

    conexion.setAutoCommit(false);

    // Calcular el total de la compra
    double total = 0;

    for (ItemCarrito item : Carrito.productos) {
        total = total + item.getSubtotal();
    }

    // Crear la venta
    String sqlVenta =
            "INSERT INTO Venta (fecha, id_cliente, total) " +
            "VALUES (datetime('now'), ?, ?)";

    java.sql.PreparedStatement sentenciaVenta =
            conexion.prepareStatement(
                    sqlVenta,
                    java.sql.Statement.RETURN_GENERATED_KEYS
            );

    sentenciaVenta.setInt(1, SesionActual.idCliente);
    sentenciaVenta.setDouble(2, total);

    sentenciaVenta.executeUpdate();

    // Obtener el id de la venta
    java.sql.ResultSet clavesVenta =
            sentenciaVenta.getGeneratedKeys();

    int idVenta;

    if (clavesVenta.next()) {

        idVenta = clavesVenta.getInt(1);

    } else {

        throw new Exception("No se pudo obtener el ID de la venta.");
    }

    clavesVenta.close();
    sentenciaVenta.close();

    // Guardar cada producto de la venta
    for (ItemCarrito item : Carrito.productos) {

        // Verificar nuevamente el stock en la base de datos
        String sqlStock =
                "SELECT stock FROM Producto WHERE id_producto = ?";

        java.sql.PreparedStatement sentenciaStock =
                conexion.prepareStatement(sqlStock);

        sentenciaStock.setInt(1, item.getIdProducto());

        java.sql.ResultSet resultadoStock =
                sentenciaStock.executeQuery();

        if (!resultadoStock.next()) {

            resultadoStock.close();
            sentenciaStock.close();

            throw new Exception(
                    "El producto " + item.getNombre() +
                    " ya no existe."
            );
        }

        int stockActual =
                resultadoStock.getInt("stock");

        resultadoStock.close();
        sentenciaStock.close();

        if (item.getCantidad() > stockActual) {

            throw new Exception(
                    "No hay suficiente stock de " +
                    item.getNombre() + "."
            );
        }

        // Insertar detalle de venta
        String sqlDetalle =
                "INSERT INTO DetalleVenta " +
                "(id_venta, id_producto, cantidad, precio_unitario, subtotal) " +
                "VALUES (?, ?, ?, ?, ?)";

        java.sql.PreparedStatement sentenciaDetalle =
                conexion.prepareStatement(sqlDetalle);

        sentenciaDetalle.setInt(1, idVenta);
        sentenciaDetalle.setInt(2, item.getIdProducto());
        sentenciaDetalle.setInt(3, item.getCantidad());
        sentenciaDetalle.setDouble(4, item.getPrecio());
        sentenciaDetalle.setDouble(5, item.getSubtotal());

        sentenciaDetalle.executeUpdate();

        sentenciaDetalle.close();

        // Descontar el stock
        String sqlActualizarStock =
                "UPDATE Producto " +
                "SET stock = stock - ? " +
                "WHERE id_producto = ?";

        java.sql.PreparedStatement sentenciaActualizar =
                conexion.prepareStatement(sqlActualizarStock);

        sentenciaActualizar.setInt(1, item.getCantidad());
        sentenciaActualizar.setInt(2, item.getIdProducto());

        sentenciaActualizar.executeUpdate();

        sentenciaActualizar.close();
    }

    // Confirmar todos los cambios
    conexion.commit();

    conexion.close();

    // Vaciar el carrito
    Carrito.productos.clear();

    cargarCarrito();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Compra realizada correctamente.\nTotal: $" + total
    );

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error al realizar la compra: " + e.getMessage()
    );
}


    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int fila = tblCarrito.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione un producto para eliminar."
        );
        return;
    }

    Carrito.productos.remove(fila);

    cargarCarrito();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Producto eliminado del carrito."
    );
    
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
VentanaInicioCliente ventana = new VentanaInicioCliente();
    ventana.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_btnVolverActionPerformed
private void cargarCarrito() {

    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblCarrito.getModel();

    modelo.setRowCount(0);

    double total = 0;

    for (ItemCarrito item : Carrito.productos) {

        double subtotal = item.getSubtotal();

        modelo.addRow(new Object[]{
            item.getNombre(),
            item.getPrecio(),
            item.getCantidad(),
            subtotal
        });

        total += subtotal;
    }

    lblTotal.setText("Total: $" + total);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaCompraCarrito().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCarrito;
    // End of variables declaration//GEN-END:variables
}
