/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tienda.Interfaces;

import Tienda.Conexion;
import Tienda.PanelFondo;

/**
 *
 * @author juanc
 */
public class VentanaDetalleCompraCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaDetalleCompraCliente.class.getName());

    /**
     * Creates new form VentanaDetalleCompraCliente
     */
    public VentanaDetalleCompraCliente(int idVenta) {
    setContentPane(new PanelFondo("/Tienda/Imagenes/fondo_abarrotes.png"));
    initComponents();
    setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/logo_galapa.png")).getImage());

    Tienda.EstiloUI.botonSecundario(btnVolver);

    cargarDetalle(idVenta);
}
private void cargarDetalle(int idVenta) {
    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) tblDetalle.getModel();

    modelo.setRowCount(0);

    try {
        java.sql.Connection conexion = Conexion.conectar();

        String sql =
                "SELECT Producto.nombre, " +
                "DetalleVenta.cantidad, " +
                "DetalleVenta.precio_unitario, " +
                "DetalleVenta.subtotal " +
                "FROM DetalleVenta " +
                "INNER JOIN Producto " +
                "ON DetalleVenta.id_producto = Producto.id_producto " +
                "WHERE DetalleVenta.id_venta = ?";

        java.sql.PreparedStatement sentencia =
                conexion.prepareStatement(sql);

        sentencia.setInt(1, idVenta);

        java.sql.ResultSet resultado =
                sentencia.executeQuery();

        while (resultado.next()) {
            modelo.addRow(new Object[]{
                resultado.getString("nombre"),
                resultado.getInt("cantidad"),
                resultado.getDouble("precio_unitario"),
                resultado.getDouble("subtotal")
            });
        }

        resultado.close();
        sentencia.close();
        conexion.close();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error al cargar el detalle: " + e.getMessage()
        );
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldtalleMiCompra = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbldtalleMiCompra.setFont(new java.awt.Font("Ubuntu Mono", 1, 48)); // NOI18N
        lbldtalleMiCompra.setForeground(new java.awt.Color(255, 255, 255));
        lbldtalleMiCompra.setText("DETALLE DE MI COMPRA");

        tblDetalle.setBackground(new java.awt.Color(153, 153, 153));
        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio Unitario", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblDetalle);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/volver.png"))); // NOI18N
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/icono_galapa_.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75)
                        .addComponent(lbldtalleMiCompra))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnVolver)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lbldtalleMiCompra)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnVolver)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
VentanaMiHistorial ventana = new VentanaMiHistorial();
ventana.setVisible(true);
this.dispose();


    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaDetalleCompraCliente(1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldtalleMiCompra;
    private javax.swing.JTable tblDetalle;
    // End of variables declaration//GEN-END:variables
}
