/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tienda.Interfaces;

import Tienda.Carrito;
import Tienda.Conexion;
import Tienda.ItemCarrito;
import Tienda.PanelFondo;

/**
 *
 * @author Aprendiz
 */
public class VentanaVerProductos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaVerProductos.class.getName());

    /**
     * Creates new form VentanaVerProductos
     */
    public VentanaVerProductos() {
        setContentPane(new PanelFondo("/Tienda/Imagenes/fondo_abarrotes.png"));
    initComponents();
    setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/fondo_abarrotes.png")).getImage());

    Tienda.EstiloUI.botonPrimario(btnAgregarAlCarrito);
    Tienda.EstiloUI.botonAcento(btnBuscar);
    Tienda.EstiloUI.botonSecundario(btnVolverMenu);
    Tienda.EstiloUI.tablaConLogo(jTable1, jScrollPane1);

        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblCategoria = new javax.swing.JLabel();
        cmbCategorias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregarAlCarrito = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("CATALOGO DE PRODUCTOS");

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBuscar.setText("Buscar:");

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/buscar.png"))); // NOI18N
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCategoria.setText("Categorias:");

        cmbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Aceites y Condimentos", "Lácteos y Huevos", "Bebidas", "Aseo del Hogar", "Snacks y Dulces", "Carnes y Embutidos", "Frutas y Verduras" }));
        cmbCategorias.addActionListener(this::cmbCategoriasActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Producto", "Precio", "Stock", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(153, 153, 153));
        lblCantidad.setText("Cantidad:");

        txtCantidad.addActionListener(this::txtCantidadActionPerformed);

        btnAgregarAlCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/agregar_carrito.png"))); // NOI18N
        btnAgregarAlCarrito.addActionListener(this::btnAgregarAlCarritoActionPerformed);

        btnVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/volver.png"))); // NOI18N
        btnVolverMenu.addActionListener(this::btnVolverMenuActionPerformed);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/icono_galapa_.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(76, 76, 76)
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVolverMenu)
                                .addGap(327, 327, 327)
                                .addComponent(lblCantidad)
                                .addGap(28, 28, 28)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarAlCarrito))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128))))
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscar)
                    .addComponent(lblCategoria))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnBuscar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(46, 46, 46)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBuscar)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(332, 332, 332)
                        .addComponent(jLabel2)
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCategoria)
                                    .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarAlCarrito)
                    .addComponent(btnVolverMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidad)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void cmbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriasActionPerformed
        // TODO add your handling code here:
        filtrarPorCategoria();
    }//GEN-LAST:event_cmbCategoriasActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void btnAgregarAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlCarritoActionPerformed
int fila = jTable1.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione un producto."
        );
        return;
    }

    int cantidad;

    try {
        cantidad = Integer.parseInt(txtCantidad.getText());

        if (cantidad <= 0) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese una cantidad válida."
            );
            return;
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese una cantidad válida."
        );
        return;
    }

    int idProducto = Integer.parseInt(
            jTable1.getValueAt(fila, 0).toString()
    );

    String nombre = jTable1.getValueAt(fila, 1).toString();

    double precio = Double.parseDouble(
            jTable1.getValueAt(fila, 2).toString()
    );

    int stock = Integer.parseInt(
            jTable1.getValueAt(fila, 3).toString()
    );

    if (cantidad > stock) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "No hay suficiente stock."
        );
        return;
    }

    ItemCarrito item = new ItemCarrito(
            idProducto,
            nombre,
            precio,
            cantidad
    );

    Carrito.productos.add(item);

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Producto agregado al carrito."
    );

    txtCantidad.setText("");

    }//GEN-LAST:event_btnAgregarAlCarritoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
String texto = txtBuscar.getText().trim();

javax.swing.table.DefaultTableModel modelo =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();

modelo.setRowCount(0);

String sql = "SELECT id_producto, nombre, precio, stock, categoria " +
             "FROM Producto WHERE nombre LIKE ?";

try (
    java.sql.Connection conexion = Conexion.conectar();
    java.sql.PreparedStatement sentencia =
            conexion.prepareStatement(sql)
) {

    sentencia.setString(1, "%" + texto + "%");

    java.sql.ResultSet resultado = sentencia.executeQuery();

    while (resultado.next()) {

        modelo.addRow(new Object[]{
            resultado.getInt("id_producto"),
            resultado.getString("nombre"),
            resultado.getDouble("precio"),
            resultado.getInt("stock"),
            resultado.getString("categoria")
        });
    }

} catch (Exception e) {

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error al buscar productos: " + e.getMessage()
    );
}

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
VentanaInicioCliente ventana = new VentanaInicioCliente();
ventana.setVisible(true);
this.dispose();

    }//GEN-LAST:event_btnVolverMenuActionPerformed
private void cargarProductos() {

    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

    modelo.setRowCount(0);

    String sql = "SELECT id_producto, nombre, precio, stock, categoria FROM Producto";

    try (
        java.sql.Connection conexion = Conexion.conectar();
        java.sql.Statement sentencia = conexion.createStatement();
        java.sql.ResultSet resultado = sentencia.executeQuery(sql)
    ) {

        while (resultado.next()) {

            modelo.addRow(new Object[]{
                resultado.getInt("id_producto"),
                resultado.getString("nombre"),
                resultado.getDouble("precio"),
                resultado.getInt("stock"),
                resultado.getString("categoria")
            });
        }

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error al cargar los productos: " + e.getMessage()
        );
    }
}
    
private void filtrarPorCategoria() {

    String categoria = cmbCategorias.getSelectedItem().toString();

    javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

    modelo.setRowCount(0);

    String sql;

    if (categoria.equals("Todas")) {

        sql = "SELECT id_producto, nombre, precio, stock, categoria FROM Producto";

    } else {

        sql = "SELECT id_producto, nombre, precio, stock, categoria " +
              "FROM Producto WHERE categoria = ?";
    }

    try (
        java.sql.Connection conexion = Conexion.conectar();
        java.sql.PreparedStatement sentencia = conexion.prepareStatement(sql)
    ) {

        if (!categoria.equals("Todas")) {
            sentencia.setString(1, categoria);
        }

        java.sql.ResultSet resultado = sentencia.executeQuery();

        while (resultado.next()) {

            modelo.addRow(new Object[]{
                resultado.getInt("id_producto"),
                resultado.getString("nombre"),
                resultado.getDouble("precio"),
                resultado.getInt("stock"),
                resultado.getString("categoria")
            });
        }

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error al filtrar productos: " + e.getMessage()
        );
    }
}/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaVerProductos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlCarrito;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JComboBox<String> cmbCategorias;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
