/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tienda.Interfaces;

import Tienda.Conexion;
import Tienda.PanelFondo;
import Tienda.SesionActual;

/**
 *
 * @author Aprendiz
 */
public class VentanaCambiarCuenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCambiarCuenta.class.getName());

    /**
     * Creates new form VentanaCambiarCuenta
     */
    private java.util.List<Integer> idsEnLista = new java.util.ArrayList<>();
    private java.util.List<String> correosEnLista = new java.util.ArrayList<>();

    public VentanaCambiarCuenta() {
        setContentPane(new PanelFondo("/Tienda/Imagenes/fondo_abarrotes.png"));
    initComponents();
    setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Tienda/Imagenes/fondo_abarrotes.png")).getImage());

    Tienda.EstiloUI.botonPrimario(btnSeleccionar);
    Tienda.EstiloUI.botonSecundario(btnCancelar);

        cargarUltimasCuentas();
    }
    
        private void cargarUltimasCuentas() {
        try {
            java.sql.Connection con = Conexion.conectar();
            java.sql.Statement st = con.createStatement();

            String sql = "SELECT id_usuario, nombre, usuario FROM Usuario " +
                         "WHERE tipo = 'CLIENTE' ORDER BY id_usuario DESC LIMIT 4";

            java.sql.ResultSet rs = st.executeQuery(sql);

            javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();
            idsEnLista.clear();
            correosEnLista.clear();

            while (rs.next()) {
                int id = rs.getInt("id_usuario");
                String nombre = rs.getString("nombre");
                String correo = rs.getString("usuario");

                modelo.addElement(nombre + " (" + correo + ")");
                idsEnLista.add(id);
                correosEnLista.add(correo);
            }

            listaCuentas.setModel(modelo);
            con.close();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar cuentas: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCuentas = new javax.swing.JList<>();
        btnSeleccionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel1.setText("CAMBIAR DE CUENTA");

        jScrollPane1.setViewportView(listaCuentas);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(this::btnSeleccionarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnSeleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSeleccionar)
                        .addGap(83, 83, 83))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        int indice = listaCuentas.getSelectedIndex();

        if (indice == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una cuenta de la lista");
            return;
        }

        int idElegido = idsEnLista.get(indice);
        String correoElegido = correosEnLista.get(indice);

        javax.swing.JPasswordField campoContrasena = new javax.swing.JPasswordField();
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
            this, campoContrasena, "Ingresa la contraseña de " + correoElegido,
            javax.swing.JOptionPane.OK_CANCEL_OPTION
        );

        if (opcion != javax.swing.JOptionPane.OK_OPTION) {
            return;
        }

        String contrasenaIngresada = new String(campoContrasena.getPassword());

        try {
            java.sql.Connection con = Conexion.conectar();

            String sql = "SELECT * FROM Usuario WHERE id_usuario = ? AND contrasena = ?";
            java.sql.PreparedStatement st = con.prepareStatement(sql);
            st.setInt(1, idElegido);
            st.setString(2, contrasenaIngresada);

            java.sql.ResultSet rs = st.executeQuery();

            if (rs.next()) {

    SesionActual.idUsuario = rs.getInt("id_usuario");
    SesionActual.nombre = rs.getString("nombre");
    SesionActual.correo = rs.getString("usuario");
    SesionActual.telefono = rs.getString("telefono");

    // Buscar el cliente correspondiente al nuevo usuario
    String sqlCliente =
            "SELECT id_cliente FROM Cliente WHERE id_usuario = ?";

    java.sql.PreparedStatement stCliente =
            con.prepareStatement(sqlCliente);

    stCliente.setInt(1, SesionActual.idUsuario);

    java.sql.ResultSet rsCliente =
            stCliente.executeQuery();

    if (rsCliente.next()) {

        SesionActual.idCliente =
                rsCliente.getInt("id_cliente");

    } else {

        SesionActual.idCliente = 0;

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "La cuenta no tiene un cliente asociado."
        );

        rsCliente.close();
        stCliente.close();
        con.close();
        return;
    }

    rsCliente.close();
    stCliente.close();

    con.close();

    javax.swing.JOptionPane.showMessageDialog(
            this,
            "Cuenta cambiada correctamente"
            
    );

    VentanaInicioCliente inicio = new VentanaInicioCliente();
    inicio.setVisible(true);
    this.dispose();

            } else {
                con.close();
                javax.swing.JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        VentanaPerfil perfil = new VentanaPerfil();
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaCambiarCuenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaCuentas;
    // End of variables declaration//GEN-END:variables
}
